events { worker_connections 1024; }

http {
    upstream backend_servers {
        # Itt fogunk skálázni: a 'backend' a Docker service neve lesz
        server backend:8080;
    }

    server {
        listen 80;
        location /api/ {
            proxy_pass http://backend_servers;
        }
        location / {
            # Itt majd a frontendet szolgáljuk ki
            proxy_pass http://frontend:5173;
        }
    }
}